### ISSUE TITLE
Re-use code

### ISSUE THREAD

**Issue by albertaparicio** [xguse/scipherPyProj#1]
Dear xguse,
I have seen your [blog post](https://scipher.wordpress.com/2010/12/02/simple-sliding-window-iterator-in-python/) about a sliding window iterator in Python, and it does just what I need.

I have tweaked your code a bit to suit my needs. My modifications make it yield a padded chunk in the end, if the sequence size is not exact.

This is the modified code:
```python
def sliding_window(sequence, win_size, step=1):
  """Returns a generator that will iterate through
  the defined chunks of input sequence.  Input sequence
  must be iterable.

  Original code by Augustine 'Gus' Dunn (xguse)
  github.com/xguse/scipherPyProj/blob/master/scipherSrc/defs/basicDefs.py"""

  # Verify the inputs
  try:
    type(sequence) == np.ndarray
  except TypeError:
    raise Exception("**ERROR** sequence must be iterable.")
  if not ((type(win_size) == int) and (type(step) == int)):
    raise Exception("**ERROR** type(winSize) and type(step) must be int.")
  if step > win_size:
    raise Exception("**ERROR** step must not be larger than winSize.")
  if win_size > len(sequence):
    raise Exception(
        "**ERROR** winSize must not be larger than sequence length.")

  # Pad sequence with zeros
  padding = np.zeros((sequence.ndim, 2), dtype=np.int)
  padding[0][1] = win_size - (sequence.shape[0] % win_size)

  padded_sequence = np.pad(
      sequence,
      padding,
      mode='constant', constant_values=0)

  # Pre-compute number of chunks to emit
  num_of_chunks = int(((len(padded_sequence) - win_size) / step) + 1)

  # Do the work
  for i in range(0, num_of_chunks * step, step):
    yield padded_sequence[i:i + win_size]
```

The thing is, I would like to use this modified function for a [library of mine](https://github.com/albertaparicio/tfglib). I would like to know if you are OK with me releasing it along with the rest of my code. I release my code under a [Lesser GPL](https://www.gnu.org/copyleft/lesser.html) license.

If you preferred your original code to be licensed under another compatible free license, I would be all right with it.

**Comment by xguse** [comment]
Go for it.

Sent from my mobile.  Please excuse any brevity, typos, and/or lack of nuance!


-------- Original Message --------

**Comment by albertaparicio** [comment]
Thank you very much
Cheers!
